config/routes.rb
UrlLongener::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy] 
  resources :urls do
    get 'long', :on => :member
  end

  match '/sign_out', to: 'sessions#destroy'

  root to: 'urls#index'

end

app/models/url.rb
class Url < ActiveRecord::Base
  attr_accessible :original_url, :long_url_hash, :click_count
  validates_presence_of :original_url
  validate :url_must_begin_with_http
  before_create :generate_long_url_hash
  belongs_to :user

  protected

  def generate_long_url_hash
    url_string = SecureRandom.hex(50)
    self.long_url_hash = url_string
  end

  def url_must_begin_with_http
    unless !!self.original_url.match(/^http/)
      errors.add(:original_url, "must begin with HTTP")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation
  validates_uniqueness_of :email
  validates_presence_of :first_name, :last_name, :email, :password, :password_confirmation
  has_many :urls
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def create_session(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  helper_method :current_user

  def same_user?(user)
    current_user == user
  end

  helper_method :same_user?
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      create_session(@user)
      redirect_to root_path
    else
      flash.now[:errors] = ['Invalid email/password combination']
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def index
    @urls = Url.all.reverse
    @url = Url.new
  end

  def create
    if current_user
      user = User.find(session[:user_id])
      @url = Url.new(params[:url])
      if @url.save
        user.urls << @url
        redirect_to url_path(@url.id)
      else
        flash.now[:errors] = @url.errors.full_messages
        @urls = Url.all.reverse
        render :index
      end
    else
      flash.now[:errors] = ['Must be signed in to longen URLs']
      @user = User.new
      render 'users/new'
    end
  end

  def show
    @url = Url.find(params[:id])
  end

  # def long
  #   url = Url.find(params[:id])
  #   url.click_count += 1
  #   url.save
  #   redirect_to "#{url.original_url}"
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      create_session(@user)
      redirect_to root_path
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @urls = @user.urls
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlLongener</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %> 
    <%= link_to "Sign Out", sign_out_path  %>
    <%= link_to "Profile", user_path(current_user.id) %>
  <% else %>
    <%= link_to "Login", new_session_path %>
    <%= link_to "Sign Up", new_user_path %>
  <% end %>

  <div class="messages">
    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <p class="errors"><%= error %></p>
      <% end %>
    <% end %>
  </div>

  <%= yield %>

</body>
</html>

app/views/urls/index.html.erb
<h1>URLs too short?</h1>
<h2>NOT A PROBLEM!!</h2>
<h2>We'll longen that URL for you. Just enter it here:</h2>

<%= form_for @url do |f| %>
  <%= f.text_field :original_url %>
  <%= f.submit "LONGEN IT" %>
<% end %>

<h3>Brilliant longened URLs of the past</h3>
<ul>
  <% @urls.each do |url| %>
    <li>
      <!-- <%= link_to url.original_url, url_path(url.id) %> -->
      <a href="<%= url.original_url %>">
        <%= url.original_url %>
      </a>
    </li>
    <li>
      <!-- <%= link_to "http://localhost.9393/url/#{url.long_url_hash}", long_url_path(url.id) %> -->
      <a href="<%= "/url/#{url.long_url_hash}" %>">
        <%= "http://localhost.9393/url/#{url.long_url_hash}" %>
      </a>
    </li>
    <br />
  <% end %>
</ul>

app/views/urls/show.html.erb
<h1>Congrats. You now have a long URL.</h1>
<h2>(No guarantees, though, if your original URL was really long.)</h2>

<p>Longened URL: 
  <a href="<%= "#{@url.long_url_hash}" %>">
    <%= "http://localhost.9393/#{@url.long_url_hash}" %>
  </a>
</p>

<p>Original URL: 
  <a href="<%= @url.original_url %>">
    <%= @url.original_url %>
  </a>
</p>

<h1><%= link_to "HOME", root_path %></h1>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %> 
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %> 
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %> 
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %></h1>
<h3><a href="mailto:#{@user.email}"></a></h3>

<h4>Here's a list of all your brilliant, longened URLs:</h4>
<ul>
  <% @urls.each do |url| %>
    <li>
      <a href="<%= url.original_url %>">
        <%= url.original_url %>
      </a>
    </li>
    <li>
      <a href="<%= "/url/#{url.long_url_hash}" %>">
        <%= "http://localhost.9393/url/#{url.long_url_hash}" %>
      </a>
    </li>
    <li>
      <% if same_user?(@user) %>
        Click count: <%= url.click_count %>
      <% end %>
    </li>
    <br />
  <% end %>
</ul>